import type { Ticket } from "../types";
//initial mock data to this will set in ticketslice initial data
export const initialTickets: Ticket[] = [
  {
    id: 1,
    title: "AI model gave incorrect clause summary",
    customerName: "John Doe",
    email: "john@example.com",
    description: "The NDA summary generated seems incomplete.",
    priority: "High",
    status: "Open",
    createdAt: "2025-10-15T10:00:00Z",
    comments: [
      { user: "Satyam Shukla", text: "We're investigating this issue.", at: "2025-10-15T11:00:00Z" },
    ],
  },
  {
    id: 2,
    title: "Wrong jurisdiction detected",
    customerName: "Alice Smith",
    email: "alice@example.com",
    description: "The model incorrectly inferred governing law as California.",
    priority: "Medium",
    status: "In Progress",
    createdAt: "2025-10-18T09:20:00Z",
    comments: [],
  },
  {
    id: 3,
    title: "Contract upload failed",
    customerName: "Michael Lee",
    email: "michael.lee@example.com",
    description: "Error while uploading PDF contract files larger than 10MB.",
    priority: "High",
    status: "Open",
    createdAt: "2025-10-16T13:10:00Z",
    comments: [
      { user: "Support Agent", text: "File size issue confirmed, devs notified.", at: "2025-10-16T14:00:00Z" },
    ],
  },
  {
    id: 4,
    title: "UI not responsive on mobile",
    customerName: "Emma Wilson",
    email: "emma.wilson@example.com",
    description: "Dashboard widgets overlap on smaller screens.",
    priority: "Low",
    status: "Resolved",
    createdAt: "2025-10-14T08:45:00Z",
    comments: [],
  },
  {
    id: 5,
    title: "Notification email delay",
    customerName: "Robert Brown",
    email: "robert.brown@example.com",
    description: "Emails are being sent 30 minutes after ticket creation.",
    priority: "Medium",
    status: "In Progress",
    createdAt: "2025-10-17T12:00:00Z",
    comments: [],
  },
  {
    id: 6,
    title: "Incorrect payment amount displayed",
    customerName: "Sophia Miller",
    email: "sophia.miller@example.com",
    description: "Payment summary shows double total for multi-item invoices.",
    priority: "High",
    status: "Open",
    createdAt: "2025-10-13T11:25:00Z",
    comments: [],
  },
  {
    id: 7,
    title: "Dark mode color contrast issue",
    customerName: "Daniel Garcia",
    email: "daniel.garcia@example.com",
    description: "Text is barely visible on dark backgrounds in reports view.",
    priority: "Low",
    status: "Open",
    createdAt: "2025-10-12T10:50:00Z",
    comments: [],
  },
  {
    id: 8,
    title: "AI clause extraction inaccurate",
    customerName: "Olivia Martinez",
    email: "olivia.martinez@example.com",
    description: "Model fails to extract arbitration clauses correctly.",
    priority: "High",
    status: "In Progress",
    createdAt: "2025-10-10T09:15:00Z",
    comments: [],
  },
  {
    id: 9,
    title: "Audit logs missing entries",
    customerName: "William Taylor",
    email: "william.taylor@example.com",
    description: "Actions between 2-4 PM not recorded in logs.",
    priority: "Medium",
    status: "Open",
    createdAt: "2025-10-09T15:00:00Z",
    comments: [],
  },
  {
    id: 10,
    title: "Two-factor authentication bug",
    customerName: "Ava Johnson",
    email: "ava.johnson@example.com",
    description: "OTP not sent when user changes phone number.",
    priority: "High",
    status: "Open",
    createdAt: "2025-10-08T07:30:00Z",
    comments: [],
  },
  {
    id: 11,
    title: "Slow dashboard load time",
    customerName: "James Anderson",
    email: "james.anderson@example.com",
    description: "Takes more than 15 seconds to load analytics data.",
    priority: "Medium",
    status: "In Progress",
    createdAt: "2025-10-07T12:00:00Z",
    comments: [],
  },
  {
    id: 12,
    title: "Exported PDF missing footer",
    customerName: "Isabella Thomas",
    email: "isabella.thomas@example.com",
    description: "Exported contracts lack company footer details.",
    priority: "Low",
    status: "Resolved",
    createdAt: "2025-10-06T11:00:00Z",
    comments: [],
  },
  {
    id: 13,
    title: "Unable to assign tickets to agents",
    customerName: "Ethan Moore",
    email: "ethan.moore@example.com",
    description: "Assign button not responding on ticket edit page.",
    priority: "High",
    status: "Open",
    createdAt: "2025-10-05T14:10:00Z",
    comments: [],
  },
  {
    id: 14,
    title: "Client login link expired early",
    customerName: "Charlotte Davis",
    email: "charlotte.davis@example.com",
    description: "Magic login link expires after 5 mins instead of 15.",
    priority: "Medium",
    status: "In Progress",
    createdAt: "2025-10-04T08:20:00Z",
    comments: [],
  },
  {
    id: 15,
    title: "Tooltip overlaps buttons",
    customerName: "Benjamin White",
    email: "benjamin.white@example.com",
    description: "Tooltip covers button actions on small screens.",
    priority: "Low",
    status: "Resolved",
    createdAt: "2025-10-03T10:00:00Z",
    comments: [],
  },
  {
    id: 16,
    title: "Attachment preview not loading",
    customerName: "Amelia Harris",
    email: "amelia.harris@example.com",
    description: "Preview shows blank when viewing attached Word files.",
    priority: "Medium",
    status: "Open",
    createdAt: "2025-10-02T09:45:00Z",
    comments: [],
  },
  {
    id: 17,
    title: "Chatbot unresponsive",
    customerName: "Liam Clark",
    email: "liam.clark@example.com",
    description: "AI assistant stops replying after 3 messages.",
    priority: "High",
    status: "In Progress",
    createdAt: "2025-10-01T14:30:00Z",
    comments: [],
  },
  {
    id: 18,
    title: "Report chart misaligned",
    customerName: "Mia Lewis",
    email: "mia.lewis@example.com",
    description: "Bar chart labels are misaligned with bars in PDF export.",
    priority: "Low",
    status: "Resolved",
    createdAt: "2025-09-30T11:15:00Z",
    comments: [],
  },
  {
    id: 19,
    title: "Broken link in email template",
    customerName: "Noah Walker",
    email: "noah.walker@example.com",
    description: "Reset password link redirects to a 404 page.",
    priority: "High",
    status: "Open",
    createdAt: "2025-09-29T13:50:00Z",
    comments: [],
  },
  {
    id: 20,
    title: "AI model timeout error",
    customerName: "Harper Allen",
    email: "harper.allen@example.com",
    description: "Clause summarization request times out after 30 seconds.",
    priority: "Medium",
    status: "Open",
    createdAt: "2025-09-28T10:00:00Z",
    comments: [],
  },
  {
    id: 21,
    title: "Multiple login sessions issue",
    customerName: "Elijah Young",
    email: "elijah.young@example.com",
    description: "Users can log in from two devices simultaneously.",
    priority: "Low",
    status: "Resolved",
    createdAt: "2025-09-27T08:10:00Z",
    comments: [],
  },
  {
    id: 22,
    title: "Export button disabled",
    customerName: "Luna King",
    email: "luna.king@example.com",
    description: "Cannot export reports even with full permissions.",
    priority: "Medium",
    status: "In Progress",
    createdAt: "2025-09-26T09:20:00Z",
    comments: [],
  },
  {
    id: 23,
    title: "User avatar upload not working",
    customerName: "Henry Scott",
    email: "henry.scott@example.com",
    description: "Profile picture upload returns 500 error.",
    priority: "Low",
    status: "Open",
    createdAt: "2025-09-25T07:45:00Z",
    comments: [],
  },
  {
    id: 24,
    title: "Search results not filtering correctly",
    customerName: "Evelyn Green",
    email: "evelyn.green@example.com",
    description: "Keyword search shows results from other users' data.",
    priority: "High",
    status: "Open",
    createdAt: "2025-09-24T13:30:00Z",
    comments: [],
  },
  {
    id: 25,
    title: "Session timeout not triggering logout",
    customerName: "Lucas Baker",
    email: "lucas.baker@example.com",
    description: "Users remain logged in even after inactivity limit.",
    priority: "Medium",
    status: "Open",
    createdAt: "2025-09-23T12:00:00Z",
    comments: [],
  },
  {
    id: 26,
    title: "Form validation not showing errors",
    customerName: "Ella Adams",
    email: "ella.adams@example.com",
    description: "Formik error messages not visible for required fields.",
    priority: "Low",
    status: "Resolved",
    createdAt: "2025-09-22T11:00:00Z",
    comments: [],
  },
  {
    id: 27,
    title: "Dashboard metrics not updating",
    customerName: "Mason Nelson",
    email: "mason.nelson@example.com",
    description: "Analytics data not refreshing automatically.",
    priority: "Medium",
    status: "In Progress",
    createdAt: "2025-09-21T09:40:00Z",
    comments: [],
  },
  {
    id: 28,
    title: "Email verification not sent",
    customerName: "Aria Carter",
    email: "aria.carter@example.com",
    description: "New users not receiving verification emails.",
    priority: "High",
    status: "Open",
    createdAt: "2025-09-20T10:20:00Z",
    comments: [],
  },
  {
    id: 29,
    title: "Pagination not working in ticket list",
    customerName: "Logan Mitchell",
    email: "logan.mitchell@example.com",
    description: "Next page button does nothing on ticket table.",
    priority: "Low",
    status: "Resolved",
    createdAt: "2025-09-19T09:10:00Z",
    comments: [],
  },
  {
    id: 30,
    title: "AI summary language incorrect",
    customerName: "Grace Perez",
    email: "grace.perez@example.com",
    description: "Model generated French summary instead of English.",
    priority: "Medium",
    status: "Open",
    createdAt: "2025-09-18T14:00:00Z",
    comments: [],
  },
  {
    id: 31,
    title: "Date format inconsistent across pages",
    customerName: "Jack Rivera",
    email: "jack.rivera@example.com",
    description: "Different date formats in dashboard and reports.",
    priority: "Low",
    status: "Resolved",
    createdAt: "2025-09-17T11:15:00Z",
    comments: [],
  },
  {
    id: 32,
    title: "Custom filters not saving",
    customerName: "Lily Murphy",
    email: "lily.murphy@example.com",
    description: "Saved filters disappear after refresh.",
    priority: "Medium",
    status: "In Progress",
    createdAt: "2025-09-16T09:00:00Z",
    comments: [],
  },
  {
    id: 33,
    title: "API returning 401 for admin user",
    customerName: "Owen Rogers",
    email: "owen.rogers@example.com",
    description: "Admin token expired unexpectedly during use.",
    priority: "High",
    status: "Open",
    createdAt: "2025-09-15T10:50:00Z",
    comments: [],
  },
  {
    id: 34,
    title: "Contract clause numbering mismatch",
    customerName: "Zoey Reed",
    email: "zoey.reed@example.com",
    description: "Numbers skip when clauses are deleted and readded.",
    priority: "Medium",
    status: "Open",
    createdAt: "2025-09-14T08:30:00Z",
    comments: [],
  },
  {
    id: 35,
    title: "Sidebar not collapsing",
    customerName: "Sebastian Cook",
    email: "sebastian.cook@example.com",
    description: "Collapse button unresponsive on dashboard sidebar.",
    priority: "Low",
    status: "Resolved",
    createdAt: "2025-09-13T07:45:00Z",
    comments: [],
  },
  {
    id: 36,
    title: "AI contract summary truncated",
    customerName: "Layla Bell",
    email: "layla.bell@example.com",
    description: "Last paragraph missing in generated summary.",
    priority: "High",
    status: "Open",
    createdAt: "2025-09-12T13:25:00Z",
    comments: [],
  },
  {
    id: 37,
    title: "Dropdown menu overlaps footer",
    customerName: "Jacob Ward",
    email: "jacob.ward@example.com",
    description: "On smaller screens, dropdown covers footer links.",
    priority: "Low",
    status: "Resolved",
    createdAt: "2025-09-11T09:50:00Z",
    comments: [],
  },
  {
    id: 38,
    title: "User deletion not removing audit logs",
    customerName: "Scarlett Gray",
    email: "scarlett.gray@example.com",
    description: "Audit entries remain even after user deletion.",
    priority: "Medium",
    status: "Open",
    createdAt: "2025-09-10T14:40:00Z",
    comments: [],
  },
  {
    id: 39,
    title: "Attachment download button broken",
    customerName: "Aiden Hughes",
    email: "aiden.hughes@example.com",
    description: "Clicking download gives empty response.",
    priority: "High",
    status: "Open",
    createdAt: "2025-09-09T12:00:00Z",
    comments: [],
  },
  {
    id: 40,
    title: "User onboarding checklist not saving progress",
    customerName: "Hannah Foster",
    email: "hannah.foster@example.com",
    description: "Progress resets on page reload.",
    priority: "Medium",
    status: "In Progress",
    createdAt: "2025-09-08T10:30:00Z",
    comments: [],
  },
  {
    id: 41,
    title: "Table sorting not persisting after refresh",
    customerName: "Carter Ward",
    email: "carter.ward@example.com",
    description: "Sorting order resets every time the page reloads.",
    priority: "Low",
    status: "Resolved",
    createdAt: "2025-09-07T13:00:00Z",
    comments: [],
  },
  {
    id: 42,
    title: "Exported Excel file missing headers",
    customerName: "Victoria Barnes",
    email: "victoria.barnes@example.com",
    description: "Excel export missing first row headers.",
    priority: "Medium",
    status: "Open",
    createdAt: "2025-09-06T11:45:00Z",
    comments: [],
  },
  {
    id: 43,
    title: "Login button not clickable on Safari",
    customerName: "Julian Hayes",
    email: "julian.hayes@example.com",
    description: "Button appears disabled only on Safari browser.",
    priority: "High",
    status: "Open",
    createdAt: "2025-09-05T09:20:00Z",
    comments: [],
  },
  {
    id: 44,
    title: "Customer feedback form not submitting",
    customerName: "Addison Price",
    email: "addison.price@example.com",
    description: "Form validation passes but API not triggered.",
    priority: "Medium",
    status: "In Progress",
    createdAt: "2025-09-04T10:40:00Z",
    comments: [],
  },
  {
    id: 45,
    title: "Duplicate ticket creation bug",
    customerName: "Matthew Cooper",
    email: "matthew.cooper@example.com",
    description: "Submitting form twice creates two tickets.",
    priority: "High",
    status: "Open",
    createdAt: "2025-09-03T09:10:00Z",
    comments: [],
  }];
  
